export const names = [
  'Hank',
  'Jacques',
  'Eddie',
  'Andy',
  'Bernard',
  'Dominic',
  'Pax',
  'Ever',
  'Lennox',
  'Hartley',
  'Hudson',
  'Mason',
  'Logan',
  'Peyton',
  'Emerson',
  'Wilder',
  'Marlowe',
  'Lennon',
  'Frankie',
  'Quincy',
  'Belly',
  'Noah',
  'Ezra',
  'Micah',
  'James',
  'Silas',
  'Charlie',
  'Cameron',
  'Reese',
  'Drew',
];

export const adjectives = [
  'sociable',
  'big-headed',
  'optimistic',
  'chatty',
  'outgoing',
  'arrogant',
  'nasty',
  'unpleasant',
  'modest',
  'generous',
  'polite',
  'unadventurous',
  'unambitious',
  'unenthusiastic',
  'unfriendly',
  'unhelpful',
  'affectionate',
  'frightening',
  'brave',
  'cheerful',
  'confident',
  'determined',
  'easygoing',
  'meticulous',
];

export const quirks = [
  'probably a vampire',
  'shoplifts',
  'a social media influencer',
  'a model',
  'an animal trainer',
  'a movie star',
  'the self-described "proud parent of two fur babies"',
  'terrifying',
  'a dentist',
  'a historical reenactor',
  'robs banks',
  'knows how to cast magic spells',
  'has a lot of friends',
  'is extremely online',
];