export const names = [
  'Hank',
  'Jacques',
  'Eddie',
  'Andy',
  'Bernard',
  'Dominic',
  'Pax',
  'Ever',
  'Lennox',
  'Hartley',
  'Hudson',
  'Mason',
  'Logan',
  'Peyton',
  'Emerson',
  'Wilder',
  'Marlowe',
  'Lennon',
  'Frankie',
  'Quincy',
  'Belly',
  'Noah',
  'Ezra',
  'Micah',
  'James',
  'Silas',
  'Charlie',
  'Cameron',
  'Reese',
  'Drew',
];

export const adjectives = [
  'sociable',
  'optimistic',
  'chatty',
  'outgoing',
  'splendid',
  'unpleasant',
  'very nice',
  'modest',
  'generous',
  'polite',
  'adventurous',
  'ambitious',
  'enthusiastic',
  'friendly',
  'helpful',
  'affectionate',
  'frightening',
  'fearsome',
  'grandiose',
  'brave',
  'a thrill-seeker',
  'cheerful',
  'confident',
  'determined',
  'easygoing',
  'meticulous',
];

export const quirks = [
  'probably a vampire',
  'a social media influencer',
  'models for toy catalogues',
  'an animal trainer',
  'has appeared in several low-budget films',
  'the self-described "proud parent of two fur babies"',
  'terrifying',
  'really interested in dental hygiene',
  'a historical reenactor',
  'robs banks',
  'knows how to cast magic spells',
  'has a lot of friends',
  'is extremely online',
  'likes to wander in the woods',
  'has built himself a dubiously-legal treehouse',
  'extremely into DIY',
  'is very good at explaining the rules of board games',
  'is a talented Vegan cook',
  'rides horses',
  'has started several businesses',
  'has a secret',
];
